-- MySQL Script generated by MySQL Workbench
-- Thu Oct 13 22:06:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Db_Cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Db_Cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Db_Cinema` DEFAULT CHARACTER SET utf8 ;
USE `Db_Cinema` ;

-- -----------------------------------------------------
-- Table `Db_Cinema`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `house` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Cinema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Cinema` (
  `cinema_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address_id` INT NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `total_halls` INT NOT NULL,
  PRIMARY KEY (`cinema_id`),
  INDEX `address_id_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `Db_Cinema`.`Address` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Seat_Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Seat_Status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Seat` (
  `seat_id` INT NOT NULL AUTO_INCREMENT,
  `hall_id` INT NOT NULL,
  `row_number` INT NOT NULL,
  `seat_number` INT NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`seat_id`),
  INDEX `status_id_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `status_id`
    FOREIGN KEY (`status_id`)
    REFERENCES `Db_Cinema`.`Seat_Status` (`status_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Hall_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Hall_Category` (
  `hall_category_id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`hall_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Hall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Hall` (
  `hall_id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `cinema_id` INT NOT NULL,
  `total_rows` INT NOT NULL,
  `total_seats` INT NOT NULL,
  `seat_id` INT NOT NULL,
  `hall_category` INT NOT NULL,
  PRIMARY KEY (`hall_id`),
  INDEX `cinema_id_idx` (`cinema_id` ASC) VISIBLE,
  INDEX `seat_id_idx` (`seat_id` ASC) VISIBLE,
  INDEX `hall_category_idx` (`hall_category` ASC) VISIBLE,
  CONSTRAINT `cinema_id`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `Db_Cinema`.`Cinema` (`cinema_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `seat_id`
    FOREIGN KEY (`seat_id`)
    REFERENCES `Db_Cinema`.`Seat` (`seat_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `hall_category`
    FOREIGN KEY (`hall_category`)
    REFERENCES `Db_Cinema`.`Hall_Category` (`hall_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Country` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Age_Limit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Age_Limit` (
  `age_limit_id` INT NOT NULL AUTO_INCREMENT,
  `limit` INT NOT NULL,
  PRIMARY KEY (`age_limit_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Movie` (
  `movie_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `duration` VARCHAR(45) NOT NULL,
  `release_year` YEAR(4) NOT NULL,
  `country_id` INT NOT NULL,
  `age_limit_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`),
  INDEX `country_id_idx` (`country_id` ASC) VISIBLE,
  INDEX `age_limit_id_idx` (`age_limit_id` ASC) VISIBLE,
  CONSTRAINT `country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `Db_Cinema`.`Country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `age_limit_id`
    FOREIGN KEY (`age_limit_id`)
    REFERENCES `Db_Cinema`.`Age_Limit` (`age_limit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Genre` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Movie_Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Movie_Genre` (
  `id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  INDEX `genre_id_idx` (`genre_id` ASC) VISIBLE,
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `genre_id`
    FOREIGN KEY (`genre_id`)
    REFERENCES `Db_Cinema`.`Genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `Db_Cinema`.`Movie` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Movie_Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Movie_Staff` (
  `staff_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Staff_Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Staff_Role` (
  `id` INT NOT NULL,
  `name` INT NOT NULL,
  `staff_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  INDEX `staff_id_idx` (`staff_id` ASC) VISIBLE,
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `staff_id`
    FOREIGN KEY (`staff_id`)
    REFERENCES `Db_Cinema`.`Movie_Staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `Db_Cinema`.`Movie` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Viewer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Viewer` (
  `viewer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NULL,
  PRIMARY KEY (`viewer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Show`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Show` (
  `show_id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `time` TIME NOT NULL,
  `hall_id` INT NOT NULL,
  PRIMARY KEY (`show_id`),
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  INDEX `hall_id_idx` (`hall_id` ASC) VISIBLE,
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `Db_Cinema`.`Movie` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hall_id`
    FOREIGN KEY (`hall_id`)
    REFERENCES `Db_Cinema`.`Hall` (`hall_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Cinema`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Cinema`.`Ticket` (
  `ticket_id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `show_id` INT NOT NULL,
  `viewer_id` INT NOT NULL,
  `seat_id` INT NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `show_id_idx` (`show_id` ASC) VISIBLE,
  INDEX `viewer_id_idx` (`viewer_id` ASC) VISIBLE,
  INDEX `seat_id_idx` (`seat_id` ASC) VISIBLE,
  CONSTRAINT `show_id`
    FOREIGN KEY (`show_id`)
    REFERENCES `Db_Cinema`.`Show` (`show_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `viewer_id`
    FOREIGN KEY (`viewer_id`)
    REFERENCES `Db_Cinema`.`Viewer` (`viewer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seat_id`
    FOREIGN KEY (`seat_id`)
    REFERENCES `Db_Cinema`.`Seat` (`seat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
